version: "3.9"

services:
  db:
    container_name: bichan_db
    image: mysql:latest
    command: --open-files-limit=30720 --max-connections=20000
    restart: always
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:${DATABASE_PORT}
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}

